-- Week 2 Coding Challenge for 7/8/19 by Travis Williamson

-- Create an EMPLOYEE table

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER,
    EMP_FIRSTNAME VARCHAR2(100),
    EMP_LASTNAME VARCHAR2(100),
    DEPARTMENT_ID NUMBER,
    SALARY NUMBER,
    EMP_EMAIL VARCHAR2(100),
    PRIMARY KEY (EMPLOYEE_ID)
);
/

-- Create a DEPARTEMENT table

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER,
    DEPARTMENT_NAME VARCHAR(100),
    PRIMARY KEY (DEPARTMENT_ID)
);
/

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID);
/

-- Create a sequence and trigger to auto-generate primary key values for both tables

-- Sequences:

CREATE SEQUENCE SQ_EMPLOYEE_PK
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE SQ_DEPARTMENT_PK
START WITH 1000
INCREMENT BY 1;

-- Triggers:

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYEE
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_EMPLOYEE_PK.NEXTVAL INTO
    :NEW.EMPLOYEE_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TR_INSERT_DEPARTMENT
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    SELECT SQ_DEPARTMENT_PK.NEXTVAL INTO
    :NEW.DEPARTMENT_ID FROM DUAL;
END;
/

-- Insert at least six employees and three departments

INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES ('Accounting');

INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES ('Sales');

INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES ('Custodial');

SELECT * FROM DEPARTMENT;
/

SELECT * FROM EMPLOYEE;
/

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Bob', 'Smith', 1002, 20000.00, 'bobsmith@company.com');
/

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Janice', 'Jones', 1002, 25000.00, 'janicejones@company.com');
/

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Kevin', 'Wilson', 1001, 50000.00, 'kevinwilson@company.com');
/

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Bertha', 'Davis', 1001, 55000.00, 'berthadavis@company.com');
/

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('William', 'James', 1000, 45000.00, 'williamjames@company.com');
/

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Rashida', 'Jackson', 1000, 43000.00, 'rashidajackson@company.com');
/

CREATE OR REPLACE PROCEDURE INSERTEMPLOYEE(EMP_FIRSTNAME IN VARCHAR2, EMP_LASTNAME IN VARCHAR2, DEPARTMENT_ID IN NUMBER, SALARY IN NUMBER, EMP_EMAIL IN VARCHAR2)
AS
BEGIN
INSERT INTO EMPLOYEE VALUES(SQ_EMPLOYEE_PK.NEXTVAL, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL);
COMMIT;
END;
/
